stages:
  - build

build_mac:
  stage: build
  tags:
    - mac
    - build
  script:
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DENABLE_OPENCV=1 .
    - make -j2
    - macpack -v -d libs src/dv-runtime

  artifacts:
    paths:
      - src/dv-runtime
      - src/libs
    expire_in: 1 day
